models/CallRequest.php
<?php

namespace app\models;

use Yii;
use yii\db\Expression;
use yii\helpers\Html;

/**
 * This is the model class for table "{{%md_call_requests}}".
 *
 * @property int $id
 * @property string $name
 * @property string $phone
 * @property string $request_date
 * @property int $proceeded
 */
class CallRequest extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%md_call_requests}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phone'], 'required'],
            [['request_date', 'update_date', 'comment'], 'safe'],
            [['proceeded'], 'integer'],
            [['name'], 'string', 'max' => 70],
            [['phone'], 'string', 'max' => 13],
            [['phone'], 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'phone' => 'Телефон',
            'request_date' => 'Дата создания',
            'update_date' => 'Дата изменения',
            'proceeded' => 'Статус',
            'comment' => 'Комментарий',
        ];
    }

    public static function statuses()
    {
        return [0 => 'Новый', 1 => 'В работе', 2 => 'Закрыт'];
    }

    public function getStatusLabel()
    {
        return self::statuses()[$this->proceeded];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->request_date = new Expression('NOW()');
            $this->proceeded = 0;
        } else {
            $this->update_date = new Expression('NOW()');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function url()
    {
        return '/call/update/' . $this->id;
    }

    public function mailText()
    {
        $body = '<h2>Запрос звонка</h2>';

        if ($this->name) {
            $body .= '<p>Имя: ' . $this->name . '</p>';
        }
        $body .= '<p>Телефон: ' . $this->phone . '</p>';
        $body .= '<p>Ссылка: ' . Html::a($this->url(), $this->url()) . '</p>';
        return $body;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (MdConfig::sendCallMail()) {
            $to = MdConfig::callEMail();
            $from = MdConfig::fromEMail();
            Yii::$app->mailer->compose()
                ->setFrom($from)
                ->setTo($to)
                ->setSubject('Запрос звонка')
                ->setHtmlBody($this->mailText())
                ->send();
        }

    }


}

controllers/RequestController.php
<?php

namespace app\controllers;

use app\models\CalculationRequest;
use app\models\CalculationRequestSearch;
use PHPUnit\Framework\Exception;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * RequestController implements the CRUD actions for CalculationRequest model.
 */
class RequestController extends Controller
{

    public $layout = 'admin';
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'create' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),

                'rules' => [
                    ['allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all CalculationRequest models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CalculationRequestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CalculationRequest model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CalculationRequest model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        try {
            $model = new CalculationRequest();
            if (Yii::$app->request->post()["CalculationRequest"]==null) {
                throw new Exception("invalid input data");
            }
            $phone = Yii::$app->request->post()['CalculationRequest']['phone'];
            $fModel = CalculationRequest::find()->where("phone like :phone", [':phone' => '%' . substr(trim($phone), -10)])->one();
            if ($fModel != null) {
                $fModel->delete();
            }
            if ($model->load(Yii::$app->request->post()) && $model->save()) {


                $userArray = ["result" => 'ok'];
                return $this->asJson($userArray);
            }
            $userArray = ["result" => 'fail'];
            return $this->asJson($userArray);
        } catch (Exception $e) {

            $userArray = ["result" => 'fail', "message" => $e->getMessage()];
            return $this->asJson($userArray);
        }

    }

    /**
     * Updates an existing CalculationRequest model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing CalculationRequest model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CalculationRequest model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CalculationRequest the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CalculationRequest::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/request/_form.php
<?php

use app\models\CalculationRequest;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CalculationRequest */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="calculation-request-form">

    <?php $form = ActiveForm::begin(); ?>


    <div class="portlet-content card">

        <ul>
            <li>
                <b>Имя</b> <span><?= $model->name ?></span>
            </li>
            <li>
                <b>Телефон</b> <span><?= $model->phone ?></span>
            </li>
            <li><b>EMail</b> <span><?= $model->email ?></span>
            </li>
            <li><b>Тиа экрана</b> <span><?= $model->typeLabel ?></span>
            </li>
            <li><b>Шаг пикселя</b> <span>P<?= $model->step?></span>
            </li>
            <li><b>Размер</b><span><?= $model->width ?> x <?= $model->height ?> </span></li>
            <li>
                <b>Сообщение</b>
                <div class="text">
                    <?= $model->message; ?>
                </div>
            </li>
            <li>
                <b>Дата заявки</b><span><?php echo (new DateTime($model->request_date))->format('H:i:s d.m') ?></span>
            </li>
            <li>
                <b>Дата
                    обновления</b><span><?php echo (new DateTime($model->update_date))->format('H:i:s d.m') ?></span>
            </li>
        </ul>
    </div>

    <div class="card">
        <?= $form->field($model, 'comment')->textarea() ?>

        <?= $form->field($model, 'proceeded')->dropDownList(CalculationRequest::statuses()) ?>
    </div>


    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/request/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CalculationRequestSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="calculation-request-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'width') ?>

    <?php // echo $form->field($model, 'height') ?>

    <?php // echo $form->field($model, 'message') ?>

    <?php // echo $form->field($model, 'request_date') ?>

    <?php // echo $form->field($model, 'proceeded') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <?php // echo $form->field($model, 'update_date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/request/index.php
<?php

use app\models\CalculationRequest;
use kartik\icons\Icon;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CalculationRequestSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = ' Запросы на расчет';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="calculation-request-index">

    <h1><?= Html::encode($this->title) ?></h1>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'phone',
            'email',
            'name',
            ['attribute'=>'proceeded',
                'filter'=>CalculationRequest::statuses(),
                'value'=>function($model){
                    return $model->getStatusLabel();
                }

            ],
            ['attribute'=>'type',
                'filter'=>CalculationRequest::types(),
                'value'=>function($model){
                    return $model->getTypeLabel();
                }

            ],
            ['attribute' => 'request_date',
                'format' => ['date', 'php:H:i.s d.m'],
                'filter'=>false
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}',
                'visible' => true,
                'buttons' => [
                    'update' => function ($url, $model) {
                        return Html::a(Icon::show('pencil'), $url, [
                            'title' => Yii::t('app', 'редактировать'),
                            'class' => "btn btn-link edit"
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a(Icon::show('trashcan'), $url, [
                            'title' => Yii::t('app', ' удалить'),
                            'class' => "btn btn-link delete",
                            'data' => [
                                'confirm' => 'Вы уверены что хотите удалить? Все данные будут потеряны',
                                'method' => 'post',
                            ],
                        ]);
                    }

                ],
            ],
        ],
    ]); ?>
</div>

views/request/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CalculationRequest */

$this->title = 'Запрос на расчет телефон: ' . $model->phone;
?>
<div class="calculation-request-update card">

    <h1><?= Html::encode($this->title) ?> <span class="status"><?= $model->statusLabel?></span></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/request/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\CalculationRequest */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Calculation Requests', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="calculation-request-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'phone',
            'email:email',
            'type',
            'width',
            'height',
            'message:ntext',
            'request_date',
            'proceeded',
        ],
    ]) ?>

</div>