controllers/BlockController.php
<?php

namespace app\controllers;

use app\models\MenuItem;
use app\models\PageBlock;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * BlockController implements the CRUD actions for PageBlock model.
 */
class BlockController extends Controller
{

    public $layout = 'admin';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

            'access' => [
                'class' => AccessControl::className(),

                'rules' => [
                    ['allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all PageBlock models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => PageBlock::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PageBlock model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PageBlock model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($back, $menu_id)
    {
        $model = new PageBlock();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect($back);
        }
        $group = MenuItem::findOne($menu_id);
        return $this->render('create', [
            'model' => $model, 'menu' => $group
        ]);
    }

    /**
     * Updates an existing PageBlock model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/page/update', 'id' => $model->menu_item_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing PageBlock model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PageBlock model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PageBlock the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PageBlock::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\CalculationRequest;
use app\models\CallRequest;
use app\models\CarouselGroup;
use app\models\ContactForm;
use app\models\LoginForm;
use app\models\MenuItem;
use app\models\RequestCalculationForm;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        $mainCarousel = CarouselGroup::findOne(['main' => 1]);
        $carousels = CarouselGroup::findAll(['main' => 0]);
        $items = MenuItem::find()->all();
        $rForm = new CalculationRequest();
        return $this->render('index', ['main' => $mainCarousel, 'rFrom' => $rForm, 'carousels' => $carousels, 'menuItems' => $items]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->renderPartial('login', [
            'model' => $model, 'layout' => 'admin'
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * @return
     */
    public static function getCallForm()
    {
        return new CallRequest();
    }

    public static function getRequestForm()
    {
        return new CalculationRequest();
    }


    public function getMenu()
    {
        $menuItems = [];
        $items = MenuItem::find()->all();
        foreach ($items as $row) {
            $menuElem = ['label' => $row->title, 'url' => ['/' . $row->alias], 'active' => mb_strpos(Url::current(), $row->alias)];
            $menuItems[] = $menuElem;
        }
        return $menuItems;
    }

    public function actionPage($alias)
    {
        $item = MenuItem::findOne(['alias' => $alias]);

        return $this->render('_page', ['model' => $item]);
    }

    public function actionRequest()
    {
        return 'request';
    }
}

views/site/_brn_equipment.php
<?php
/**
 * Created by PhpStorm.
 * User: pavel.chermyanin
 * Date: 22/08/2018
 * Time: 0:31
 */
?>

<section class="bnrs bnr-block">
        <h2>Поставляемое оборудование</h2>
        <ul>
            <li>
                <a href="" class="card">
                    <div class="img" style="background-image: url('img/card-img.png');">

                    </div>
                    <div class="text">

                        <h4>Светодиодные модули </h4>
                        <p>В производстве используются светодиоды DIP и SMD производителей Nation Star и Epistar. По
                            заказу
                            устанавливаем светодиоды японской компании Nichia.</p>
                        <p>Каждый модуль имеет влагозащиту IP68.</p>
                    </div>
                </a>
            </li>
            <li>
                <a href="" class="card">
                    <div class="img" style="background-image: url('img/card-img.png');">

                    </div>
                    <div class="text">

                        <h4>Светодиодные модули </h4>
                        <p>В производстве используются светодиоды DIP и SMD производителей Nation Star и Epistar. По
                            заказу
                            устанавливаем светодиоды японской компании Nichia.</p>
                        <p>Каждый модуль имеет влагозащиту IP68.</p>
                    </div>
                </a>
            </li>
            <li>
                <a href="" class="card">
                    <div class="img" style="background-image: url('img/card-img.png');">

                    </div>
                    <div class="text">

                        <h4>Светодиодные модули </h4>
                        <p>В производстве используются светодиоды DIP и SMD производителей Nation Star и Epistar. По
                            заказу
                            устанавливаем светодиоды японской компании Nichia.</p>
                        <p>Каждый модуль имеет влагозащиту IP68.</p>
                    </div>
                </a>
            </li>
            <li>
                <a href="" class="card">
                    <div class="img" style="background-image: url('img/card-img.png');">

                    </div>
                    <div class="text">

                        <h4>Светодиодные модули </h4>
                        <p>В производстве используются светодиоды DIP и SMD производителей Nation Star и Epistar. По
                            заказу
                            устанавливаем светодиоды японской компании Nichia.</p>
                        <p>Каждый модуль имеет влагозащиту IP68.</p>
                    </div>
                </a>
            </li>
        </ul>
    </section>

views/site/_calc.php
<?php
/**
 * Created by PhpStorm.
 * User: pavel.chermyanin
 * Date: 22/08/2018
 * Time: 0:40
 */
?>


<div class="right-column">
    <form class="calculator" name="calculator">
        <h4>Расчет стоимости</h4>
        <input type="hidden" name="step" class="step"/>
        <input type="hidden" name="type" class="type"/>
        <input type="hidden" name="price" class="price"/>
        <div class="slider-group">
            <p class="info">
                <label for="height">Высота экрана</label>
            <span class="selected-value">
                        <span id="widthInfo"></span>
                    <span class="unit"></span>
                </span>
            </p>
            <!--<div class="slider" data-min="0" data-max="" data-step="" data-name="width"></div>-->
            <input class="slider" name="width" id="widthSlider" data-info-field="widthInfo"
                   data-slider-id='ex1Slider' type="text" data-slider-min="0"
                   data-slider-max="20" data-slider-step="1" data-slider-value="14"/>
        </div>
        <div class="slider-group">
            <p class="info">
                <label for="height">Высота экрана</label>
            <span class="selected-value">
                        <span id="heightInfo"></span>
                    <span class="unit"></span>
                </span>
            </p>
            <input class="slider" name="height" id="heightSlider" data-info-field="heightInfo"
                   data-slider-id='ex2Slider' type="text" data-slider-min="0"
                   data-slider-max="20" data-slider-step="1" data-slider-value="14"/>
        </div>
        <label class="bold">Шаг пикселя</label>
        <ul class="check-buttons" id="pixels">
           
        </ul>
        <label class="bold">Конструкция</label>
        <div class="check-button-imaged">
            <div>
                <ul class="check-buttons">
                    <li>
                        <button type="button" class="button button-checker active" data-img="img/img-1">
                            Реечный
                        </button>
                    </li>
<!--                    <li>-->
<!--                        <button type="button" class="button button-checker" data-img="">Сетка</button>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <button type="button" class="button button-checker" data-img="">Кластерный</button>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <button type="button" class="button button-checker" data-img="">Прозрачный</button>-->
<!--                    </li>-->
                </ul>
            </div>
            <div class="img-for-option">
                <img id="img-for-option" src=""/>
            </div>
        </div>
        <p class="summary">
        </p>
        <input data-modal="#requestModal" class="button button-big  modal-btn" value="Заявка на точный расчет">
    </form>
    <p class="note clr-gray">Цена приблизительная. Отправьте заявку на точный расчет, мы вам перезвоним, сообщим
        стоимость и поможем выбрать подходящий экран.</p>
</div>

views/site/_carousel.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\CarouselGroup */
/* @var $index integer */
?>
<?php

$carousel = '';
$index = (isset($index)) ? $index : 0;
$carouselID = 'carousel_' . $index;
$numberOfSlides = sizeof($model->slides);
if ($numberOfSlides == 0) {
    die;
}

$innerCarousel = ' <div class="carousel-inner">';
$i = 0;
foreach ($model->slides as $slide) {
    $active = ($i == 0) ? 'active' : '';
    $innerCarousel .= '<div class="item ' . $active . '">
                        <div class="img">
                            <img class="" src="'.$slide->img_url.'">
                        </div>';
    if (isset($slide->content)) {
        $innerCarousel .= '<div class="text">
                            <h4>'.$slide->header.'</h4>
                                '.$slide->content.'
                        </div>';
    }
    $innerCarousel .= '</div>';
    $i++;
}
$innerCarousel .= '</div>';


$carouselBlock = '<div id="' . $carouselID . '" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">';

for ($i = 0; $i < $numberOfSlides; $i++) {
    $active = ($i == 0) ? 'active' : '';
    $carouselBlock .= '<li data-target="#' . $carouselID . '" data-slide-to="' . $active . '"></li>';
}

$carouselBlock .= ' </ol>';
$carouselBlock .= $innerCarousel;
$carouselBlock .= '<a class="left carousel-control" href="#' . $carouselID . '" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#' . $carouselID . '" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>';

if ($model->main) {
    $carousel = '<section class="carousel-section main-carousel">';
    $carousel .= $carouselBlock;

} else {
    $left = ($index % 2 == 0) ? 'left' : 'right';
    $carousel = '<section class="carousel-section commented-carousel ' . $left . '">';
    $carousel .= '<div class="carousel-column">';
    if (isset($model->warranty)) {
        $carousel .= '<div class="warranty-block">
                            <div class="comment">' . $model->warranty . '
                         </div>
                    </div>';
        //$carousel .= '<div class="carousel-column">';
    }
    $carousel .= $carouselBlock;
    $carousel .= '</div>';
    $carousel .= "<div class='text'>
        <h2>$model->header</h2>
        $model->content
    </div>";

}
$carousel .= '    <div class="clear"></div>';
$carousel .= '</section>';
?>

<?php echo $carousel; ?>

views/site/_img_menu.php
<?php
/* @var $this yii\web\View */
/* @var $items app\models\MenuItem[] */
use yii\helpers\Url;


$itemsHTML = '';

foreach ($items as $item) {
    $itemHtml = '<li>
                <a href="/site/' . $item->alias.'" class="card">';
    $itemHtml .= ' <div class="img" style="background-image: url(\'' . $item->icon_img_url . '\');"></div>';
    $itemHtml .= '<div class="text">
                        <h4>' . $item->title . '</h4>
                        <p>' . $item->big_title . '</p>
                    </div>';
    $itemHtml .= '</a></li>';
    $itemsHTML.=$itemHtml;
}

?>


<section class="bnrs bnrs-menu">
    <ul>
        <?= $itemsHTML?>
    </ul>
    <div class="clear"></div>
</section>

views/site/_nav.php
<?php
/**
 * Created by PhpStorm.
 * User: pavel.chermyanin
 * Date: 19/08/2018
 * Time: 22:56
 */

views/site/_page.php
<?php
/* @var $this yii\web\View */
use yii\web\View;

/* @var $model app\models\MenuItem */
$this->params['editlink'] = ['page/update/'.$model->id];
?>

<div class="wrapper">
    <div class="content-body colored">
        <article class="left-column">
            <h1><?= $model->title ?></h1>
            <div class="lit">
                <?= $model->lead ?>
            </div>
            <div class="img main-img">
                <?= \yii\helpers\Html::img($model->main_img_url) ?>
            </div>
            <h2><?= $model->block_title ?></h2>
            <?= $this->render('/block/index', ['blocks' => $model->blocks]); ?>

        </article>
        <?= $this->render('_calc') ?>
        <div class="clear"></div>
    </div>
    <!-- banners -->

    <?php
    $this->registerJs(
        "  fillCalc('$model->alias');",
        View::POS_READY,
        'calc-fill'
    );
    ?>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use app\models\CalculationRequest;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $main CarouselGroup */
/*@var $carousels  CarouselGroup[]*/
/*@var $menuItems MenuItem[]*/


$this->title = '3 Art: Медиафасады';
$this->params['editlink'] = ['carousel/index'];
?>


<div class="content-body colored">
    <section class="presentation">
        <h1>Светодиодные экраны и медиафасады</h1>
        <p>Проектируем, производим, доставляем и монтируем по всей России</p>
        <?php if (!empty(\app\models\MdConfig::presFile())): ?>
            <a href="<?php echo \app\models\MdConfig::presFile(); ?>" class="button button-big">
                Скачать презентацию
            </a>
        <?php endif; ?>
    </section>
    <?= $this->render('_carousel', [
        'model' => $main,
    ])

    ?>

    <?= $this->render('_img_menu', [
        'items' => $menuItems,
    ]) ?>


    <?php
    foreach ($carousels as $index => $carousel) {
        echo $this->render('_carousel', [
            'model' => $carousel, 'index' => $index
        ]);
    }
    ?>

    <section class="calculator">
        <?php $form = ActiveForm::begin(['action' => ['/request/create'], 'options' => ['id' => 'req', 'data-success' => "#successRequestModal", 'data-error' => '#errorModal', 'data-method' => "post", 'method' => 'post']]); ?>
        <div class="col-sm-4 col-xs-12">
            <h2><span class="bordered">Заявка на расчет</span></h2>
            <p>Получите расчёт проекта и консультацию специалиста абсолютно бесплатно и без каких-либо
                обязательств.</p>
        </div>
        <div class="col-sm-4 col-xs-12">
            <?= $form->field($rFrom, 'name')->textInput(['maxlength' => true]) ?>
            <?= $form->field($rFrom, 'phone')->textInput(['maxlength' => true]) ?>
            <?= $form->field($rFrom, 'email')->textInput(['maxlength' => true]) ?>
            <?= $form->field($rFrom, 'type')->dropDownList(CalculationRequest::types()); ?>
        </div>
        <div class="col-sm-4 col-xs-12">
            <div class="slider-group">
                <p class="info">
                    <label for="width">Ширина экрана</label>
                <span class="selected-value">
                    <span id="widthInfo"></span>
                    <span class="unit"></span>
                 </span>
                </p>

                <!--<div class="slider" data-min="0" data-max="" data-step="" data-name="width"></div>-->
                <input class="slider" name="CalculationRequest[width]" id="widthSlider" data-info-field="widthInfo"
                       data-slider-id='ex1Slider' type="text" data-slider-min="0"
                       data-slider-max="20" data-slider-step="1" data-slider-value="14"/>
            </div>
            <div class="slider-group">
                <p class="info">
                    <label for="height">Высота экрана</label>
            <span class="selected-value">
                        <span id="heightInfo"></span>
                    <span class="unit"></span>
                </span>
                </p>

                <input class="slider" name="CalculationRequest[height]" id="heightSlider" data-info-field="heightInfo"
                       data-slider-id='ex2Slider' type="text" data-slider-min="0"
                       data-slider-max="20" data-slider-step="1" data-slider-value="14"/>
            </div>
            <?= $form->field($rFrom, 'message')->textarea(['id' => 'message']) ?>
            <?= Html::submitButton('Отправить заявку', ['class' => 'button button-big']) ?>
        </div>

        <?php ActiveForm::end(); ?>
        <div class="clear"></div>
    </section>
    <?php
    $this->registerJs(
        "fillCalconMain('mediafacades');",
        View::POS_READY,
        'calc-fill'
    );
    ?>
    <?php
    $this->registerJs(
        " $('form#req').on('beforeSubmit', function(e){
 
    console.log($('#req').serializeArray());
   
     $.post({
       url: '/request/create', 
       dataType: 'json',
       data:$('#req').serializeArray(),
       success: function(data) {
         
          $($(e.target).data('success')).modal('show');
          console.log(data);
       },
     error: function(err){
     $($(e.target).data('error')).modal('show');
 
       }
    });
       return false;
    });    ",
        View::POS_READY,
        'form-handler'
    );
    ?>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход в систему';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginContent('@app/views/layouts/admin.php'); ?>
<div class="site-login">
    

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label} <div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-7\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-2 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>
<?php $this->endContent();?>