controllers/BlockController.php
<?php

namespace app\controllers;

use app\models\MenuItem;
use app\models\PageBlock;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * BlockController implements the CRUD actions for PageBlock model.
 */
class BlockController extends Controller
{

    public $layout = 'admin';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

            'access' => [
                'class' => AccessControl::className(),

                'rules' => [
                    ['allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all PageBlock models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => PageBlock::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PageBlock model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PageBlock model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($back, $menu_id)
    {
        $model = new PageBlock();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect($back);
        }
        $group = MenuItem::findOne($menu_id);
        return $this->render('create', [
            'model' => $model, 'menu' => $group
        ]);
    }

    /**
     * Updates an existing PageBlock model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/page/update', 'id' => $model->menu_item_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing PageBlock model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PageBlock model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PageBlock the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PageBlock::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/page/_form.php
<?php

use dosamigos\tinymce\TinyMce;
use kartik\icons\Icon;
use yii\helpers\Html;
use yii\web\JsExpression;
use yii\web\View;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\MenuItem */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'big_title')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'icon_img_url')->hiddenInput(['maxlength' => true])->label(false); ?>

    <div class="form-group">
        <label>Иконка для меню на главной</label>
        <div class="photo photo-square-small" id="photo">
            <?php
            $hi = 0;
            if (!empty($model->icon_img_url)) :
                echo Html::img($model->icon_img_url, ['id' => "icon_img_url"]);
                $hi = 1;
            endif; ?>
            <div class="inner-dot">
                <a id="imageUpload" href="javascript:;">Загрузить</a>
                <img src="" id="img" style="display: none"/>
                <?= \troy\ImageUpload\ImageUpload::widget(
                    [
                        'targetId' => 'imageUpload',//html dom id
                        'config' => [
                            'name' => 'file',
                            'action' => Yii::$app->getUrlManager()->createUrl(['file/upload']),
                            'onComplete' => new JsExpression("function(fileName, responseJSON){
                var json = $.parseJSON(responseJSON);
                 $('#img').attr('src', '/'+json.store);
                 $('#page-icon_img_url').val('/'+json.store);
                 $('#img').show();
                 $('#imageUpload').hide();
                 
                 }")
                        ]
                    ]
                ); ?>

            </div>
            <div class="delete-hover">
                <?= Html::a('<span class="glyphicon glyphicon-trash"></span>', null, ['class' => 'delete', 'title' => 'Удалить изображение']); ?>

            </div>
            <?php
            $this->registerJs(
                "var hideloadi = " . $hi . "
                if(hideloadi){
                    $('#photo .inner-dot').hide();
                    $('#photo .delete-hover').show();
                }
                
                $('#clean').on('click', function() { 
                        $('#page-icon_img_url').val('');
                        $('#photo .inner-dot').show();
                        $('#imageUpload').show();
                        $('#img').attr('src', '');
                        $('#img').hide();
                        $('#main_img').hide();
                        $('.delete-hover').hide();
                    });",
                View::POS_READY,
                'my-button-handler'
            );
            ?>
        </div>
    </div>
    <?= $form->field($model, 'main_img_url')->hiddenInput(['maxlength' => true])->label(false); ?>
    <div class="form-group">
        <label>Основное изображение</label>
        <div class="article-photo photo" id="photoMain">
            <?php
            $h = 0;

            if (!empty($model->main_img_url)) :
                echo Html::img($model->main_img_url, ['id' => "main_img"]);
                $h = 1;
            endif; ?>
            <div class="inner-dot">
                <a id="imageUploadMain" href="javascript:;">Загрузить</a>
                <img src="" id="imgMain" style="display: none"/>
                <?= \troy\ImageUpload\ImageUpload::widget(
                    [
                        'targetId' => 'imageUploadMain',//html dom id
                        'config' => [

                            'name' => 'file',
                            'action' => Yii::$app->getUrlManager()->createUrl(['file/upload']),

                            'onComplete' => new JsExpression("function(fileName, responseJSON){
                console.log(responseJSON);
                console.log(fileName);
                var json = $.parseJSON(responseJSON);
                 $('#imgMain').attr('src', '/'+json.store);
                 $('#page-main_img_url').val('/'+json.store);
                 $('#imgMain').show();
                 $('#imageUploadMain').hide();
                 
                 }")
                        ]
                    ]
                ); ?>

            </div>
            <div class="delete-hover">
                <?= Html::a('<span class="glyphicon glyphicon-trash"></span>', null, ['class' => 'delete', 'title' => 'Удалить изображение']); ?>

            </div>
            <?php
            $this->registerJs(
                "var hideloadMain = " . $h . "
                if(hideloadMain){
                    $('#photoMain .inner-dot').hide();
                    $('#photoMain .delete-hover').show();
                }
                
                $('#photoMain .delete').on('click', function() { 
                        $('#page-main_img_url').val('');
                        $('#photoMain .inner-dot').show();
                        $('#imageUploadMain').show();
                        $('#imgMain').attr('src', '');
                        $('#imgMain').hide();
                        $('#main_img').hide();
                        $('#photoMain .delete-hover').hide();
                    });",
                View::POS_READY,
                'my-button-handler-main'
            );
            ?>
        </div>
    </div>


    <?php echo $form->field($model, 'lead', ['template' => '{label}{hint}{input}'])
        ->hint('Выводиться в списке статей и между заголовком и основным изображением. Должна быть краткой и не должна содержать картинок.')
        ->widget(TinyMce::class, [
            'options' => ['rows' => 14],
            'language' => 'ru',

            'clientOptions' => [
                'content_css' => ['//' . Yii::$app->request->baseUrl . '/css/mce.css'],
                'plugins' => [
                    "advlist autolink lists link charmap anchor",
                    "code fullscreen",
                    "contextmenu"
                ],
                'toolbar' => "undo redo | styleselect | bold italic | bullist numlist ",
                'automatic_uploads' => false,
            ]
        ]); ?>

    <?=
    $form->field($model, 'block_title')->textInput();
    ?>


    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <?php if (!$model->isNewRecord): ?>
        <div class="card">
            <h1>Блоки на
                странице <?= Html::a(Icon::show('plus'), ['/block/create', 'back' => Yii::$app->request->url, 'menu_id' => $model->id], ['class' => 'btn btn-outline-success']) ?> </h1>
            <?php foreach ($model->blocks as $index => $item) :
                $class = ($index % 2 == 0) ? 'left' : 'right';
                $textClass = '';
                ?>
                <div class="article-content <?= $class ?>">
                    <?php if (!empty($item->img_url)): ?>
                        <div class="img-column">
                            <div class="img">
                                <?= Html::img($item->img_url) ?>
                            </div>
                        </div>

                    <?php else:
                        $textClass = 'wide';
                    endif; ?>
                    <div class="text <?= $textClass?>">
                        <?= $item->content ?>
                    </div>
                    <div class="delete-hover">
                        <?= Html::a(Icon::show('pencil'), ['/block/delete', 'id' => $item->id], ['class' => 'delete', 'title' => 'Удалить блок']); ?>
                        <?= Html::a(Icon::show('trashcan'), ['/block/update', 'id' => $item->id, 'back' => Yii::$app->request->url], ['class' => 'update', 'title' => 'Редактировать']); ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

views/page/_view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\MenuItem */

?>



<div class="intro">
    <h1><?= Html::a($model->title, ['/article/view', 'id' => $model->id]) ?></h1>
    <p class="lit"><?= $model->lead ?></p>
    <?= isset($model->main_img_url)?Html::img($model->main_img_url):'<div></div>' ?>

    <p class="info"><span class="date"><?= $model->published ?></span><span class="author"><?= $model->author ?></span>
    </p>
</div>

views/page/admin.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\grid\GridView;
use kartik\icons\Icon;

Icon::map($this);
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Страницы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-index">

    <h1><?= Html::encode($this->title); ?> <?= Html::a(Icon::show('plus'), ['create'], ['class' => 'btn btn-outline-success']) ?> </h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'title',
            'big_title',
            'lead',
            [
                'format'=>"image", // or other formatter
                'attribute' => 'icon_img_url',
                'contentOptions' => ['class' => 'img-preview-small']
            ],
            [
                'format'=>"image", // or other formatter
                'attribute' => 'main_img_url',
                'contentOptions' => ['class' => 'img-preview']
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}',
                'visible' => true,
                'buttons' => [

                    'update' => function ($url, $model) {
                        return Html::a(Icon::show('pencil'), $url, [
                            'title' => Yii::t('app', 'редактировать'),
                            'class' => "btn btn-link edit"
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a(Icon::show('trashcan'), $url, [
                            'title' => Yii::t('app', ' удалить'),
                            'class' => "btn btn-link delete",
                            'data' => [
                            'confirm' => 'Вы уверены что хотите удалить? Все данные будут потеряны',
                            'method' => 'post',
                        ],
                        ]);
                    }

                ],
            ],
        ],
    ]); ?>
</div>

views/page/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\MenuItem */

$this->title = 'Добавить страницу';
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['admin']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create card">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/page/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->params['editlink'] = ['article/admin'];
?>
<?php $this->beginContent('@app/views/layouts/main.php'); ?>

    <div class="article-clean list">
        <div class="container">
            <div class="row">

                    <h1><?= Html::encode($this->title) ?></h1>


                    <?= ListView::widget([
                        'dataProvider' => $dataProvider,
                        'layout' => "{items}\n{pager}",
                        'options'=>['tag'=>'div', 'class'=>'col-lg-8 col-xl-8 offset-lg-2 offset-xl-2'],
                        'itemView' => '_view',
                        'pager' => [

                            'prevPageLabel' => '&larr; Новые',
                            'nextPageLabel' => 'Предыдущие &rarr;',
                        ],
                    ]) ?>
            </div>
        </div>
    </div>


<?php $this->endContent(); ?>

views/page/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MenuItem */

$this->title = 'Редактировать страницу: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['admin']];
$this->params['breadcrumbs'][] = $model->title;
?>
<div class="article-update card">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/page/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\MenuItem */

$this->title = $model->title;

$this->params['editlink'] = ['article/update', 'id'=>$model->id];

$og='';
$og=$og.'<meta property="og:title" content="'.$model->title.'"/>';
$og=$og.'<meta property="og:image" content="'.Yii::getAlias('@web').$model->main_img_url.'"/>';
$og=$og.'<meta property="og:image:width" content="200"/>';

$og=$og.'<meta property="og:type" content="article"/>';
$og=$og.'<meta property="og:url" content="'.Yii::$app->request->absoluteUrl.'"/>';
$og=$og.'<meta property="article:author" content="'.$model->author.'"/>';

$this->params['og']=$og;

?>
<?php $this->beginContent('@app/views/layouts/main.php'); ?>
<article class="article-clean">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-xl-8 offset-lg-2 offset-xl-2">
                <div class="intro">
                    <h1><?= Html::encode($this->title) ?></h1>
                    <div class="lit"><?php echo $model->lead; ?>
                    </div>
                    <div class="article-photo photo">
                        <?= Html::img($model->main_img_url, ["class"=>"img-fluid"]); ?>
                    </div>
                </div>
                <div class="text">
                    <?php echo $model->content; ?>
                    <div class="likely likely-big" data-url="<?= Yii::$app->request->absoluteUrl?>">
                        <div class="twitter"></div>
                        <div class="facebook"></div>
                        <div class="vkontakte"></div>
                        <div class="telegram"></div>
                        <div class="odnoklassniki"></div>
                    </div>

                    <p class="info"><span class="date"> 
                            <?=
                            \app\common\OutputFormatter::publishedDate($model->published);

                            ?></span><span
                            class="author"><?= Html::encode($model->author); ?></span></p>
                </div>
            </div>
        </div>
    </div>
</article>
<?php $this->endContent(); ?>